apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-vectordb-sync.fullname" . }}
  labels:
    {{- include "k8s-vectordb-sync.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "k8s-vectordb-sync.selectorLabels" . | nindent 4 }}
  ports:
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
