apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: k8s-vectordb-sync
    app.kubernetes.io/managed-by: kustomize
  name: selfsigned-issuer
  namespace: system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: k8s-vectordb-sync
    app.kubernetes.io/managed-by: kustomize
  name: metrics-certs
  namespace: system
spec:
  isCA: false
  commonName: k8s-vectordb-sync-metrics
  dnsNames:
  - controller-manager-metrics-service.k8s-vectordb-sync-system.svc
  - controller-manager-metrics-service.k8s-vectordb-sync-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: metrics-server-cert
